### ISSUE TITLE
NHD geodatabase

### ISSUE THREAD

**Issue by jbeaulie** [USEPA/climateBenefits#3]
@bryanparthum 
'Climate Benefits of Nutrient Management.Rmd' assumes a copy of the NHD geodatabase can be found in 'store/'.  Given the size of the file, we added it to .gitignore so it is not at github.  I noticed that your local clone does not have a copy of this file.  You could copy my file and paste it into your clone, or we could move the .gdb out of the repo and read it from Chris's OneDrive folder. 
 I guess the benefit is that we wouldn't have multiple copies of that relatively large file hanging around.

**Comment by bryanparthum** [comment]
@jbeaulie 
Ha... sorry, I was in desperate need to recover a couple of quick GB of HD space (remote and don't have my external drive here) and deleted it from my local clone. I'll put it back in there once I have my external back (why they give us poor-performing laptops with 250gb of HD space is beyond me... seems like a worthy investment, yes, I know this is on the record). 

We can keep it in the repo (and ignore) just so everything is in one place. Thanks!

**Comment by jbeaulie** [comment]
@bryanparthum 
FYI...you can have IT install a higher capacity HD in your government laptop.  Your office will need to purchase the hardware, but big HDs are relatively cheap.  Coordinate with IT ahead of time to make sure the HD is compatible with your system.  I upgraded to a 1TB solid state HD and it has made a world of difference.
