### ISSUE TITLE
Can't knit Neptunes .rmd

### ISSUE THREAD

**Issue by jbeaulie** [USEPA/climateBenefits#4]
@bryanparthum 

Although we decided not to impliment Neptune's approach for estimating uncertainty, I want to make sure I can knit the .rmd.  This may turn out to be useful to future Jake.  Although I can run all the code chunks from the .rmd, RStudio throws the following error when knitting:
![image](https://user-images.githubusercontent.com/6340340/106192746-99d96e00-617a-11eb-900e-fc12e828e236.png)

Could you give it a shot?  Note that I pushed a modified version of the .rmd where I dialed back the number of simulations from 1000 to 10.  This is just to expedite testing.  When we get the bug worked out I'll delete this file.  ClimateBenefitsofNutrientManagement_withErrorNeptune_10.Rmd

**Comment by bryanparthum** [comment]
Hey!

I'll take a look tonight! But the first half is actually just a warning, right? The second seems to be the case that the working directory is off... I've actually been having a heck of a time getting `here()` to behave accordingly, I'm finding it has something to do with .Rproj files not behind discovered by it's internal processes correctly.

Will touch base after I run it.

Bryan



___________________
Bryan Parthum, Economist
U.S. EPA, Office of Policy
National Center for Environmental Economics
202.564.1045

**Comment by bryanparthum** [comment]
@jbeaulie,
 
I'm getting the same error you are. Something is tripping up on the temporary html files. Seems that it's not actually writing the file that it is calling. 

The other markdown docs in the repo seem to be running fine, so I would rule out something internal to R/.Rmd/html.

Given that the YAML's are the same between markdown docs, I'm a little stumped for the time being. I can't dig into this more right now, but I hope that confirming it also fails for me is helpful. Sorry! I'll likely be a little disengaged until about Feb 20th when our first big asks from the EO's are expired.

**Comment by jbeaulie** [comment]
@bryanparthum 

I removed the cache=TRUE setting from the code chunks and the _10.Rmd file knitted without issue.  The .Rmd with 10,000 simulations seemed to hang up after ~12 hours on my laptop, so I clicked the 'stop' button in the RMarkdown console in RStudio.  Surprisingly, the .html was knit correctly.  I guess this is 'good enough'.

**Comment by jbeaulie** [comment]
.Rmd with 10,000 simulations and cache=TRUE removed ran to completion without incident on my VM.
